version: "3.4"
services:
  app:
    image: demo
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
#      - ./src:/app/src
    container_name: blog
