version: "3.4"
services:
  app:
    image: demo
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    container_name: blog
